### ISSUE TITLE
RealWorld is not working, copy of reality needed?

### ISSUE THREAD

**Issue by nerkn** [solidjs/solid-realworld#12]
Currently Realworld api's failing, 
ie:
`https://api.realworld.io/api/tags`

`"Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 9)"`

so the app, as in real world. May be backend be decoupled

**Comment by ryansolid** [comment]
Thanks. Interestingly the official API was recently updated and we changed to it. I wonder if the official repo has reported the issue. Might be worth checking that out. We are reliant on the provided upstream API.

**Comment by ryansolid** [comment]
API seems up again. So I guess we're good now.
