### ISSUE TITLE
Backend is not working

### ISSUE THREAD

**Issue by bannndi** [solidjs/solid-realworld#8]
Seems something to do with CORS.

![image](https://user-images.githubusercontent.com/3719008/133595193-b0c40398-cacd-4a6b-924b-fb40fe6453ce.png)

![image](https://user-images.githubusercontent.com/3719008/133595440-25011298-9539-4304-978a-a15ae0e8cd5f.png)

In Demo link app not working too:

![image](https://user-images.githubusercontent.com/3719008/133594238-76c34228-4ca6-4b86-993e-4937cef82a40.png)

**Comment by ryansolid** [comment]
Yeah looks like the main repo has been having issues that have been effecting every implementation(some are server rendered so the initial page is fine but when you navigate you hit this). They setup a temporary fix but all the implementations will need to change their URL endpoints. https://github.com/gothinkster/realworld/issues/702
